[package]
name = "p2p-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.48.0"
futures = "0.3.25"
async-std = { version = "1.12.0", features = ["attributes"] }
chrono = "0.4.23"