apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: peer-to-peer-platform
  labels:
    name: node
spec:
  nodeSelector:
    nodelabel: node-01
  containers:
    - name: container-a
      image: bsilveira1974/dht-app:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5353