apiVersion: v1
kind: Pod
metadata:
  name: pod-c
  namespace: peer-to-peer-platform
spec:
  containers:
    - name: pod-c
      image: bsilveira1974/mdns-pod-b:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4242
    nodeSelector:
      nodetype=worker