apiVersion: v1
kind: Pod
metadata:
  name: pod-d
  namespace: peer-to-peer-platform
  labels:
    name: node-m02
spec:
  nodeSelector:
    nodelabel: node-02
  containers:
    - name: container-a
      image: bsilveira1974/dht-app:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5353