apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  namespace: peer-to-peer-platform
spec:
  nodeSelector:
    nodelabel: node-01
  containers:
  - name: container-a
    image: bsilveira1974/mdns-app:1.0
    imagePullPolicy: IfNotPresent
  - name: container-b
    image: bsilveira1974/mdns-app:1.0
    imagePullPolicy: IfNotPresent