apiVersion: v1
kind: Pod
metadata:
  name: pod-d
  namespace: peer-to-peer-platform
spec:
  containers:
    - name: pod-d
      image: bsilveira1974/mdns-app:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4242
  nodeSelector:
    nodetype: worker