apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  namespace: peer-to-peer-platform
spec:
  nodeSelector:
    nodelabel: node-01
  containers:
    - name: container-a
      image: bsilveira1974/p2p-pod-b:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4242